# permissions for end users to view bridgejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bridgejob-viewer-role
rules:
- apiGroups:
  - bridgejob.ibm.com
  resources:
  - bridgejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bridgejob.ibm.com
  resources:
  - bridgejobs/status
  verbs:
  - get
