kind: BridgeJob
apiVersion: bridgejob.ibm.com/v1alpha1
metadata:
  name: slurmjob
spec:
  resourceURL: {{RESOURCE_URL}}
  image: soerenmetje/bridge-operator-slurm-pod:v0.0.2 # TODO build and push image quay.io/ibmdpdev . Then replace here
  resourcesecret: {{RESOURCE_SECRET}}
  imagepullpolicy: Always
  updateinterval: 20
  jobdata:
    jobscript: |
      #!/bin/bash
      echo "$PWD"
    scriptlocation: inline
  jobproperties: |
    {
    "nodes":"1",
    "partition": "skylake",
    "tasks": 1,
    "name": "bridge-test0",
    "current_working_directory": "/home/ec2-user/test/",
    "environment": {
      "PATH": "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin",
      "LD_LIBRARY_PATH": ""
      }
    }
