kind: BridgeJob
apiVersion: bridgeoperator.ibm.com/v1alpha1
metadata:
  name: bridgejob-ray
spec:
  image: quay.io/ibmdpdev/ray-pod:v0.0.1
  imagepullpolicy: Always
  resourceURL: {{RESOURCE_URL}}
  resourcesecret: {{RESOURCE_SECRET}}
  updateinterval: 20
  jobdata:
    jobscript: {{JOBSCRIPT}}
    scriptlocation: s3
    scriptmetadata: {{SCRIPT_MD}}
    jobparameters: {{PARAMS}}
    scriptextralocation: s3
  s3storage:
    s3secret: {{S3_SECRET}}
    endpoint: {{ENDPOINT}}
    secure: false
  s3upload:
    bucket: {{BUCKET}}
