apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-runner
  namespace: kubeflow
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - namespaces
    verbs:
      - get
      - patch
      - watch
      - list
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-runner
subjects:
  - kind: ServiceAccount
    name: pipeline-runner
roleRef:
  kind: ClusterRole
  name: pipeline-runner
  apiGroup: rbac.authorization.k8s.io
